package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import DTO.MessageDTO;
import control.RequestControl;
import model.User;
import model.enumeration.EnumBankMessages;
import org.jgroups.Message;

import javax.swing.JFrame;

/**
 *
 * @author weth
 */
public class MainScreen extends javax.swing.JFrame {

    private User user;
    private RequestControl requestControl;
    /**
     * Creates new form MainScreen
     */
    public MainScreen(User user, RequestControl requestControl) {
        this.user = user;
        this.requestControl = requestControl;
        setTitle(user.getName());
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    private void logout() throws Exception{
        MessageDTO messageDTO = new MessageDTO();
        messageDTO.setObject(user);
        messageDTO.setBankMessage(EnumBankMessages.LOGOUT_CLIENT);
        requestControl.channel.send(new Message(null, null, messageDTO));
    }

    private void showExtracts() throws Exception {
        MessageDTO messageDTO = new MessageDTO();
        messageDTO.setObject(user.getCpf());
        messageDTO.setBankMessage(EnumBankMessages.GET_EXTRACT);
        requestControl.channel.send(new Message(null, null, messageDTO));
    }

    private void showBalance() throws Exception{
        MessageDTO messageDTO = new MessageDTO();
        messageDTO.setObject(user.getCpf());
        messageDTO.setBankMessage(EnumBankMessages.GET_BALANCE);
        requestControl.channel.send(new Message(null, null, messageDTO));
    }

    private void showAmount() throws Exception{
        MessageDTO messageDTO = new MessageDTO();
        messageDTO.setObject(null);
        messageDTO.setBankMessage(EnumBankMessages.GET_AMOUNT);
        requestControl.channel.send(new Message(null, null, messageDTO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transferButton = new javax.swing.JButton();
        balanceButton = new javax.swing.JButton();
        extractButton = new javax.swing.JButton();
        amountButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        transferButton.setText("Transferência");
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        balanceButton.setText("Saldo");
        balanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceButtonActionPerformed(evt);
            }
        });

        extractButton.setText("Extrato");
        extractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractButtonActionPerformed(evt);
            }
        });

        amountButton.setText("Montante");
        amountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PARANA INTERNET BANKING");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(transferButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extractButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amountButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutButton)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transferButton)
                    .addComponent(balanceButton)
                    .addComponent(extractButton)
                    .addComponent(amountButton)
                    .addComponent(logoutButton))
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        TransferScreen transferScreen = new TransferScreen(this, true, requestControl);
        transferScreen.setUser(user);
        transferScreen.setVisible(true);
    }//GEN-LAST:event_transferButtonActionPerformed

    private void balanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceButtonActionPerformed
        try {
            showBalance();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_balanceButtonActionPerformed

    private void extractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractButtonActionPerformed
        try {
            showExtracts();
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_extractButtonActionPerformed

    private void amountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountButtonActionPerformed
        try {
            showAmount();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_amountButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        try {
            logout();
        } catch (Exception e) {
            e.printStackTrace();
        }
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton amountButton;
    private javax.swing.JButton balanceButton;
    private javax.swing.JButton extractButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton transferButton;
    // End of variables declaration//GEN-END:variables
}
